# Generated by Django 5.1 on 2024-08-22 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='toDoList',
            fields=[
                ('todo_id', models.AutoField(primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('todo', models.CharField(max_length=50)),
                ('last_update', models.DateTimeField(default=datetime.datetime(2024, 8, 22, 22, 52, 47, 910069))),
            ],
            options={
                'db_table': 'todo_list',
            },
        ),
    ]
